apiVersion: starburstdata.com/v1
kind: Presto
metadata:
  name: presto-test
spec:
  coordinator:
    cpuLimit: 0.5
    cpuRequest: 0.5
    memoryAllocation: 1Gi
  nameOverride: presto-test
  service:
    name: presto-test
  worker:
    count: 2
    cpuLimit: 0.5
    cpuRequest: 0.5
    memoryAllocation: 1Gi
